#can use any supported distro as base - --build-arg
ARG BASE_IMAGE=myorg/myapp:latest
FROM $BASE_IMAGE

RUN apt-get update && apt-get install -y python3 python3-dev python3-pip python3-setuptools python3-pil \
        iputils-ping git curl

RUN pip3 install esphome tornado esptool

#mkdir -p $uData/config

COPY platformio.ini /opt/pio/ 

#install platformio libs and reinstall toolchain to specified version 
RUN (platformio run -d /opt/pio; echo "Done") && rm -rf /opt/pio/ \
    && rm -rf /root/.platformio/packages/toolchain-xtensa32 \
    && curl -sSL -o /toolchain-xtensa32.tar.gz \
         https://github.com/esphome/esphome-docker-base/releases/download/v1.4.0/toolchain-xtensa32.tar.gz \
    && tar -xzf /toolchain-xtensa32.tar.gz -C /root/.platformio/packages/ \
    && rm /toolchain-xtensa32.tar.gz \
    \
    && rm -rf /root/.platformio/packages/toolchain-xtensa \
    && curl -sSL -o /toolchain-xtensa.tar.gz \
         https://github.com/esphome/esphome-docker-base/releases/download/v1.4.0/toolchain-xtensa.tar.gz \
    && tar -xzf /toolchain-xtensa.tar.gz -C /root/.platformio/packages/ \
    && rm /toolchain-xtensa.tar.gz

WORKDIR /config

COPY run-esphome.sh /
RUN chmod a+x /run-esphome.sh && ln -sf /run-esphome.sh /r
ENTRYPOINT ["/r"]
CMD [ "startup"]
